### ISSUE TITLE
[Crash]  Unable to load cursor texture!

### ISSUE THREAD

**Issue by MimzyFang** [wired-tomato/WayGL#10]
this issue started happening after I changed the plasma 6 curser theme note 
i am using the flatpack version of prism launcher and am using quilt as the modloader
the minecraft version I'm on is 1.20.1
here is my log 
https://mclo.gs/7tDeHvc

**Comment by wired-tomato** [comment]
Please make sure the following paths can be read in your flatpack configuration:
- $HOME/.local/share/icons/<theme>/cursors/left_ptr (read only)
- $HOME/.icons/<theme>/cursors/left_ptr (read only)
- /usr/share/icons/<theme>/cursors/left_ptr (read only)

Additionally make sure the following programs can be accessed:
- xdg-icon-resource (to update the icon system)
- gsettings (to query for cursor theme & size)


Aside from that version 1.1.1 should fix this issue by defaulting to a prepackaged cursor when failing to load the system cursor.
