### ISSUE TITLE
zink-renderer  seems unsupported

### ISSUE THREAD

**Issue by ghost** [wired-tomato/WayGL#25]
as the title says  
without zink, everything's fine  
i want vulkan over gl-4.6 and wayland window-creation  
same result without the waygl mod  
also: all cases are the same with fabric-0.16.2  
not quilt-related

___information___
distro: nobara (fedora) -40
jdk: graalvm-ce-21.0.2+13.1
minecraft: 1.21.1
lwjgl: 3.3.3
quilt-loader: 0.26.4-beta.3
*or*
fabric-loader: 0.16.2

___showcase___

https://github.com/user-attachments/assets/e72cd311-f7b6-4aef-a3f4-7b9884c04ca8

buffer seems to be empty
idk why
pls fix

**Comment by ghost** [comment]
@wired-tomato
@moehreag

**Comment by CamperSamu** [comment]
Did you manage to fix this?
I am having this issue too on Arch, KDE 6 + Nividia open-dkms drivers 560

**Comment by ghost** [comment]
yes, do not use zink renderer :+1:
i think it's an issue within zink-renderer not detecting the framebuffer properly
also: opengl is fine for most use-cases regarding to minecraft

**Comment by ghost** [comment]
@CamperSamu

**Comment by CamperSamu** [comment]
This is not a valid solution.
If I use WayGL (or similar mods) with OGL I get terrible frames.
For now Xwayland is good enough but there's a recession somewhere because earlier this year it was working.

**Comment by lunarydess** [comment]
well sucks to be u maybe fix it urself? ![image](https://github.com/user-attachments/assets/5379ee09-3990-4c2e-84d4-32a2d615eb92)

**Comment by CamperSamu** [comment]
I found a workaround in the meantime, apparently something is off with the current AUR configuration for nVidia drivers or something changed around v560.
The 565 build from CachyOS repos (partially) fixes the issue.
