### ISSUE TITLE
Gnome Window Borders not working properly

### ISSUE THREAD

**Issue by Enderteck** [wired-tomato/WayGL#5]
On gnome, the boders don't show correctly.

https://github.com/BoyOrigin/glfw-wayland

Is there a way for the mod to make minecraft use this glfw library on gnome by default ?

**Comment by 0hStormy** [comment]
Have had the same issue

**Comment by 0hStormy** [comment]
Found a fix, in Prism Launcher, in the instance settings, go to Workarounds, and the Check Native Libraries and Use native GLFW install.

**Comment by Enderteck** [comment]
> Found a fix, in Prism Launcher, in the instance settings, go to Workarounds, and the Check Native Libraries and Use native GLFW install.

I installed this mod to do that tho lol. I don't want to do it for every instance i create.

**Comment by wired-tomato** [comment]
Newest version of the mod now has an option to use a native GLFW library in config with ModMenu integration via MidnightLib.

![image](https://github.com/wired-tomato/WayGL/assets/116689698/88781cbb-4a0d-4aa7-aab9-c573a14bb051)
![image](https://github.com/wired-tomato/WayGL/assets/116689698/57b408ab-2b10-4303-ba59-0d90c05fd1f9)

**Comment by Enderteck** [comment]
Very nice !
