### ISSUE TITLE
"Wayland: The platform does not support setting cursor position" on KDE 5.27

### ISSUE THREAD

**Issue by MangoDev1** [wired-tomato/WayGL#6]
GPU: NVIDIA GTX 1660 SUPER
Driver: Proprietary (535)
WM: KWin 5.27.10
Launcher: Prism
MC Version: 1.20.1

The game runs fine, but when I open or close any menu, the game can't seem to re-center the cursor, and it prints this error in the logs every time:
![image](https://github.com/wired-tomato/WayGL/assets/94928669/c38fe07d-b1ad-48d7-8172-0f523c696795)

I don't know if this is something to do with the drivers, the fact that 5.27 is a little old in terms of Wayland compatibility (still waiting for 6.0), or if it's an actual problem/incompatibility with WayGL. Everything else works flawlessly, but the cursor centering seems to not work as of now.

**Comment by TheNukeLore** [comment]
I also have this issue.

**Comment by TheNukeLore** [comment]
https://github.com/glfw/glfw/blob/8e6c8d7effc54f8aecd30eda17069588298f4ada/src/wl_window.c#L2535-L2539 seems its something with wayland and or glfw, apparently wayland doesnt support mouse warping

**Comment by wired-tomato** [comment]
Should be fixed with [Virtual Cursor](https://github.com/wired-tomato/WayGL/blob/1.20.x/src/main/kotlin/net/wiredtomato/waygl/VirtualCursor.kt) implementation in newest version for 1.20-1.20.4 (backport is coming later)
